apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
{{- if .Values.config.inlineData }}
data:
{{.Values.config.inlineData | indent 2}}
{{- end }}
{{- if .Values.config.inlineBinaryData }}
binaryData:
{{.Values.config.inlineBinaryData | indent 2}}
{{- end }}
